"""this code will help you creating sap notes"""

print("press enter if you do not know the answer")
case_number = input("enter the case number: ")
issue_description = input("enter the issue description: ")
error = input("which is the error message? ")
new_configuration = input("is it a new configuration? ")
product = input("enter the product category utm/xg/red/sophos_central etc.. ")
product_formatted = product.lower()
firmware_version = input("which is the firmware version = ")
access_id_uid = input("access id or UID number = ")
sophos_case_ftp_username = input("sophos case ftp username = ")
sophos_case_ftp_password = input("sophos case ftp password = ")
frequency_of_the_issue = input("if issue is still present how many times a day or weeks issue happen? ")
timestamp = input("do you know day hour and min issue happened last time? ")
source_details = input("can you provide the details of the source (ip,username,etc..) ")

print("\n")
print("######### SAP Problem: " + case_number + " #########" )
print("issue description = " + issue_description)
print("error = " + error)
print("\n")
print("######### DATA: ######### ")
print("new configuration = " + new_configuration) 
print("product = " + product_formatted)
print("firmware version = " + firmware_version)
print("remote access details = " + access_id_uid)
print("sophos ftp server credentials = " + sophos_case_ftp_username + ":" + sophos_case_ftp_password)
print("frequency of the issue = " + frequency_of_the_issue)
print("test details:")
print("    timestamp = " + timestamp)
print("    source details = " + source_details)
print("\n")
print("######### Assessment: ######### ")
print("\n")
print("######### Troubleshooting steps: ######### ")
print("\n")
print("######### POA: ######### ")
print("\n")
print("######### LOG ANALYSIS: ######### ")
print("\n")
print("######### LOGS: ######### ")
print("\n")
print("######### FOLLOWED KB: ######### ")
print("\n")
print("######### COMMANDS USED FOR LOG COLLECTION: ######### ") 
